#print('I love python')
#print('what is your name?')
#MyName = input()
#print ('your name is '+MyName)
print(3+3)
print(4.30-.530)
print(5432+5432)
num1=input()
num2=input()
print(int(num1)+int(num2))
